name: fuel_repository
description: Dart package which plays as a repository for fuel types.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
