name: favorite_repository
description: Dart package which plays as a repository for favorites.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  equatable: ^2.0.0
  shared_preferences: ^2.0.5

  listing_repository:
    path: ../../packages/listing_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
